version: '3.8'

services:

  react:
    labels:
      shipyard.route: '/'
    build:
      args:
        REACT_APP_BUILD_ARG: 'static docker-compose build arg'
      context: .
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    ports:
      - '5000:5000'
