version: '3.8'

services:

  react:
    labels:
      shipyard.route: '/'
    build:
      context: .
    volumes:
      - './src:/app/src'
      - './public:/app/public'
    ports:
      - '3000:3000'

  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'obscure-user'
      POSTGRES_PASSWORD: 'obscure-password'
      POSTGRES_DB: 'app'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - 'shipyard-nfs:/mnt/nfs'
    ports:
      - '5432'

volumes:
  postgres:
  shipyard-nfs:
